
import { useState, useEffect } from 'react';
import Navigation from '@/components/Navigation';
import { BadgeCheck, TrendingUp, Clock, Users, BarChart3, Award } from 'lucide-react';
import { cn } from '@/lib/utils';

const factors = [
  {
    title: "Credibility Score",
    description: "Measures the trustworthiness, expertise, and authority of an individual in their field through verified credentials, awards, and recognitions.",
    icon: BadgeCheck,
    metrics: [
      "Academic and professional credentials",
      "Industry awards and recognitions",
      "Published works and peer citations",
      "Professional affiliations",
      "Verified achievements"
    ]
  },
  {
    title: "Relevance Factor",
    description: "Evaluates how timely and important an individual's contributions are to their field or industry, considering both current impact and future potential.",
    icon: TrendingUp,
    metrics: [
      "Timeliness of contributions",
      "Innovation and originality",
      "Media mentions and expert citations",
      "Thought leadership in emerging trends",
      "Adaptability to industry changes"
    ]
  },
  {
    title: "Consistency Rating",
    description: "Analyzes the stability and reliability of an individual's performance, output quality, and presence over time.",
    icon: Clock,
    metrics: [
      "Longevity in the industry",
      "Regularity of contributions",
      "Quality consistency across works",
      "Sustained relevance over time",
      "Resilience through industry changes"
    ]
  },
  {
    title: "Engagement Metrics",
    description: "Measures the depth and quality of interactions generated by an individual's work, not just quantity of followers or views.",
    icon: Users,
    metrics: [
      "Quality of audience interactions",
      "Conversation depth and sentiment",
      "Community building capability",
      "Cross-platform engagement",
      "Conversion of engagement to action"
    ]
  }
];

const faqItems = [
  {
    question: "How is the InfluenceIQ score calculated?",
    answer: "The InfluenceIQ score is a composite rating on a scale of 1-100 that combines our four core metrics: Credibility, Relevance, Consistency, and Engagement. Each component is weighted based on industry-specific considerations, with our proprietary algorithm accounting for both quantitative data and qualitative assessments from our panel of industry experts."
  },
  {
    question: "How often are the rankings updated?",
    answer: "Our rankings are updated monthly to reflect new achievements, publications, and significant shifts in industry dynamics. Trending indicators show month-over-month changes, giving visibility to rising stars and established figures maintaining their influence."
  },
  {
    question: "Can individuals or companies request to be ranked?",
    answer: "We do not accept applications or payments to be included in our rankings. Our system identifies influential individuals based on objective data gathering and analysis. However, you can suggest corrections to existing profile information through our verification process."
  },
  {
    question: "What makes InfluenceIQ different from social media metrics?",
    answer: "Unlike platforms that measure primarily follower counts or engagement rates, InfluenceIQ evaluates substantive impact, credibility, and sustained relevance. Our system recognizes that true influence often extends beyond digital presence to include academic contributions, industry innovation, and real-world impact."
  },
  {
    question: "How do you prevent gaming the system?",
    answer: "Our algorithm includes multiple safeguards against artificial inflation of metrics. We analyze patterns over time, verify achievements through trusted sources, and incorporate diverse data points that cannot be easily manipulated. Additionally, our expert review process provides human oversight to identify anomalies."
  }
];

export default function Methodology() {
  const [activeSection, setActiveSection] = useState("");
  const [visibleSections, setVisibleSections] = useState<string[]>([]);
  
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setVisibleSections((prev) => [...prev, entry.target.id]);
          } else {
            setVisibleSections((prev) => prev.filter((id) => id !== entry.target.id));
          }
        });
      },
      { threshold: 0.3 }
    );
    
    const sections = document.querySelectorAll("section[id]");
    sections.forEach((section) => observer.observe(section));
    
    return () => {
      sections.forEach((section) => observer.unobserve(section));
    };
  }, []);
  
  useEffect(() => {
    if (visibleSections.length > 0) {
      setActiveSection(visibleSections[0]);
    }
  }, [visibleSections]);
  
  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      window.scrollTo({
        top: element.offsetTop - 100,
        behavior: "smooth"
      });
    }
  };
  
  return (
    <div className="min-h-screen">
      <Navigation />
      
      <div className="pt-28 pb-16">
        {/* Hero section */}
        <section className="py-16 relative overflow-hidden">
          <div className="absolute inset-0 z-[-1] bg-gradient-to-b from-influence-accent/10 to-transparent" aria-hidden="true" />
          
          <div className="content-container text-center max-w-3xl mx-auto">
            <h1 className="text-4xl md:text-5xl font-bold mb-6 animate-fade-in">Our Methodology</h1>
            <p className="text-xl text-muted-foreground mb-8 animate-fade-in animation-delay-100">
              How we measure true influence in a world of fleeting metrics
            </p>
            
            <div className="flex justify-center mb-12 animate-fade-in animation-delay-200">
              <div className="p-1.5 rounded-full bg-white dark:bg-gray-800 shadow-subtle border border-border">
                <div className="flex gap-1">
                  <button 
                    onClick={() => scrollToSection("overview")}
                    className={cn(
                      "px-4 py-2 text-sm font-medium rounded-full transition-colors",
                      activeSection === "overview" 
                        ? "bg-influence-accent text-white" 
                        : "hover:bg-gray-100 dark:hover:bg-gray-700"
                    )}
                  >
                    Overview
                  </button>
                  <button 
                    onClick={() => scrollToSection("factors")}
                    className={cn(
                      "px-4 py-2 text-sm font-medium rounded-full transition-colors",
                      activeSection === "factors" 
                        ? "bg-influence-accent text-white" 
                        : "hover:bg-gray-100 dark:hover:bg-gray-700"
                    )}
                  >
                    Ranking Factors
                  </button>
                  <button 
                    onClick={() => scrollToSection("process")}
                    className={cn(
                      "px-4 py-2 text-sm font-medium rounded-full transition-colors",
                      activeSection === "process" 
                        ? "bg-influence-accent text-white" 
                        : "hover:bg-gray-100 dark:hover:bg-gray-700"
                    )}
                  >
                    Our Process
                  </button>
                  <button 
                    onClick={() => scrollToSection("faq")}
                    className={cn(
                      "px-4 py-2 text-sm font-medium rounded-full transition-colors",
                      activeSection === "faq" 
                        ? "bg-influence-accent text-white" 
                        : "hover:bg-gray-100 dark:hover:bg-gray-700"
                    )}
                  >
                    FAQ
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
        
        {/* Overview section */}
        <section id="overview" className="py-16 bg-white dark:bg-gray-950">
          <div className="content-container max-w-4xl mx-auto">
            <div className="max-w-3xl mx-auto text-center mb-12">
              <h2 className="text-3xl font-bold mb-4 animate-fade-in">Moving Beyond Likes and Followers</h2>
              <p className="text-lg text-muted-foreground animate-fade-in animation-delay-100">
                In today's digital landscape, it's easy to confuse popularity with genuine influence. 
                InfluenceIQ was created to establish a more meaningful standard that measures what truly matters.
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-white dark:bg-gray-900 border border-border rounded-xl p-6 shadow-subtle transition-all duration-300 hover:shadow-card animate-fade-in animation-delay-200">
                <h3 className="text-xl font-semibold mb-4 text-influence-error">The Old Approach</h3>
                <ul className="space-y-3">
                  <li className="flex items-start">
                    <span className="text-influence-error mr-2">✕</span>
                    <span>Overemphasis on follower counts and engagement rates</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-influence-error mr-2">✕</span>
                    <span>Prioritizing viral moments over consistent quality</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-influence-error mr-2">✕</span>
                    <span>Easily manipulated metrics through paid services</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-influence-error mr-2">✕</span>
                    <span>No verification of expertise or credentials</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-influence-error mr-2">✕</span>
                    <span>Focus on quantity over quality of content</span>
                  </li>
                </ul>
              </div>
              
              <div className="bg-white dark:bg-gray-900 border border-influence-accent/30 rounded-xl p-6 shadow-subtle transition-all duration-300 hover:shadow-card animate-fade-in animation-delay-300">
                <h3 className="text-xl font-semibold mb-4 text-influence-success">The InfluenceIQ Approach</h3>
                <ul className="space-y-3">
                  <li className="flex items-start">
                    <span className="text-influence-success mr-2">✓</span>
                    <span>Comprehensive evaluation of verified achievements</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-influence-success mr-2">✓</span>
                    <span>Analysis of sustained impact over time</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-influence-success mr-2">✓</span>
                    <span>Emphasis on content quality and original contributions</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-influence-success mr-2">✓</span>
                    <span>Industry-specific benchmarking against peers</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-influence-success mr-2">✓</span>
                    <span>Multi-dimensional scoring across credibility, relevance, consistency and engagement</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        
        {/* Ranking Factors section */}
        <section id="factors" className="py-16 bg-gray-50 dark:bg-gray-900">
          <div className="content-container max-w-4xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold mb-4">Ranking Factors</h2>
              <p className="text-lg text-muted-foreground max-w-3xl mx-auto">
                Our ranking algorithm evaluates individuals across four key dimensions to calculate 
                a comprehensive InfluenceIQ score.
              </p>
            </div>
            
            <div className="space-y-12">
              {factors.map((factor, index) => (
                <div 
                  key={index}
                  className="bg-white dark:bg-gray-950 rounded-xl border border-border overflow-hidden shadow-subtle transition-all duration-300 hover:shadow-card animate-fade-in"
                  style={{ animationDelay: `${100 + index * 100}ms` }}
                >
                  <div className="p-6 md:p-8">
                    <div className="flex flex-col md:flex-row md:items-center gap-4 md:gap-6 mb-6">
                      <div className={cn(
                        "w-12 h-12 rounded-full flex items-center justify-center",
                        "bg-influence-accent/10 text-influence-accent"
                      )}>
                        <factor.icon size={24} />
                      </div>
                      
                      <div>
                        <h3 className="text-xl font-semibold">{factor.title}</h3>
                        <p className="text-muted-foreground mt-1">
                          {factor.description}
                        </p>
                      </div>
                    </div>
                    
                    <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-4">
                      <h4 className="font-medium mb-3">Key Metrics:</h4>
                      <ul className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-2">
                        {factor.metrics.map((metric, i) => (
                          <li key={i} className="flex items-start">
                            <span className="text-influence-accent mr-2">•</span>
                            <span className="text-sm">{metric}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
        
        {/* Process section */}
        <section id="process" className="py-16 bg-white dark:bg-gray-950">
          <div className="content-container max-w-4xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold mb-4">Our Ranking Process</h2>
              <p className="text-lg text-muted-foreground max-w-3xl mx-auto">
                How we transform raw data into meaningful influence scores
              </p>
            </div>
            
            <div className="relative">
              <div className="absolute left-[29px] top-8 bottom-0 w-0.5 bg-influence-accent/30" aria-hidden="true" />
              
              <div className="space-y-12">
                {[
                  {
                    number: "01",
                    title: "Data Collection",
                    description: "We gather information from multiple sources, including verified public databases, academic publications, industry records, and digital platforms. Our data pipeline processes both quantitative metrics and qualitative information.",
                    icon: BarChart3
                  },
                  {
                    number: "02",
                    title: "Initial Analysis",
                    description: "Raw data undergoes preliminary processing to identify patterns and establish baseline metrics for each individual. We normalize scores across different industries to ensure fair comparisons within their respective fields.",
                    icon: TrendingUp
                  },
                  {
                    number: "03",
                    title: "Verification & Validation",
                    description: "Our team manually verifies key achievements and credentials to ensure accuracy. We also employ cross-referencing techniques to validate data points across multiple sources, reducing the impact of potential manipulation.",
                    icon: BadgeCheck
                  },
                  {
                    number: "04",
                    title: "Algorithm Application",
                    description: "Our proprietary algorithm calculates scores across all four dimensions (Credibility, Relevance, Consistency, and Engagement). The algorithm adjusts for industry-specific factors and applies appropriate weighting to each component.",
                    icon: Clock
                  },
                  {
                    number: "05",
                    title: "Final Scoring",
                    description: "The composite InfluenceIQ score is calculated on a scale of 1-100, representing the individual's overall influence within their field. Scores are refreshed monthly to capture changes in relevance and impact.",
                    icon: Award
                  }
                ].map((step, index) => (
                  <div 
                    key={index}
                    className="relative flex animate-fade-in"
                    style={{ animationDelay: `${100 + index * 100}ms` }}
                  >
                    <div className="flex-shrink-0">
                      <div className="relative z-10 h-14 w-14 rounded-full bg-influence-accent flex items-center justify-center text-white shadow-sm">
                        <step.icon size={20} />
                      </div>
                    </div>
                    
                    <div className="ml-6">
                      <div className="flex items-center">
                        <div className="bg-influence-accent/10 px-2 py-0.5 rounded text-sm font-medium text-influence-accent">
                          {step.number}
                        </div>
                        <h3 className="text-xl font-semibold ml-3">{step.title}</h3>
                      </div>
                      <p className="mt-2 text-muted-foreground">
                        {step.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>
        
        {/* FAQ section */}
        <section id="faq" className="py-16 bg-gray-50 dark:bg-gray-900">
          <div className="content-container max-w-3xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold mb-4">Frequently Asked Questions</h2>
              <p className="text-lg text-muted-foreground">
                Common questions about our ranking methodology
              </p>
            </div>
            
            <div className="space-y-6">
              {faqItems.map((item, index) => (
                <div
                  key={index}
                  className="bg-white dark:bg-gray-950 border border-border rounded-xl overflow-hidden shadow-subtle animate-fade-in"
                  style={{ animationDelay: `${100 + index * 100}ms` }}
                >
                  <details className="group">
                    <summary className="flex justify-between items-center cursor-pointer p-6">
                      <h3 className="text-lg font-medium">{item.question}</h3>
                      <span className="ml-4 flex-shrink-0 flex items-center justify-center w-6 h-6 rounded-full border border-border group-open:rotate-180 transition-transform duration-200">
                        <ChevronDown size={14} />
                      </span>
                    </summary>
                    <div className="px-6 pb-6 pt-2 text-muted-foreground">
                      <p>{item.answer}</p>
                    </div>
                  </details>
                </div>
              ))}
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
